#!/usr/bin/perl

# $Id $

#######################################################################
### scrape-wowhead.perl                                             ###
### Fetches data from wowhead to build default categories for TBag. ###
### Copyright 2007 Shefki, All Rights Reserved!                     ###
### Not for redistribution!                                         ###
#######################################################################

#################
### Libraries ###
#################
use lib '/Users/breser/lib/perl/lib/perl5/site_perl';
use strict;
use WWW::Mechanize;

##############
### Config ###
##############

# URL snipets used to get what we need
my $wowhead_url = 'http://www.wowhead.com/';
my $item_tag = '?item=';
my $trade_filter = '?items&filter=cr=86;crv=0;crs=';
my $poison_filter = '?items=15.-5&filter=cl=4';

# bagtype names as the key with an item id to one of these types of 
# bags.
my %bag_types = (
  'SOUL' => '21342',
	'HERB' => '22252',
	'ENG'  => '30748',
	'ENCH' => '21858',
	'GEM'  => '24270',
	'MINE' => '29540',
	'QUIV' => '18714',
	'AMMO' => '19320'
);

# Name of a trade as the key with the relative URL
# for the filter to get the items made by that trade.
my %trades = (
  'Alchemy' => "${trade_filter}1",
	'Blacksmithing' => "${trade_filter}2",
  'Enchanting', => "${trade_filter}4",
	'Engineering' => "${trade_filter}5",
	'Jewelcrafting' => "${trade_filter}7",
 	'Leatherworking' => "${trade_filter}8",
 	'Tailoring' => "${trade_filter}10"
);
my %secondary = (
  'Cooking' => "${trade_filter}3",
	'First Aid' => "${trade_filter}6"
);
my %skills = (
	'Mining' => "${trade_filter}9",
	'Poisons' => "$poison_filter"
);

# Quality splits to avoid the 200 item limit of wowhead's search
my %quality_levels =  (
	'Epic+' => ';qu=4:5:6',
	'Rare' => ';qu=3',
	'Uncommon' => ';qu=2',
	'Poor/Common' => ';qu=0:1'
);

##############
### Output ###
##############

# Save current time for output
my $time = time();

my %TBag_ContainerItems;
my %TBag_Reagents;
my %TBag_TradeCreations;
for my $trade (keys %trades) {
	$TBag_TradeCreations{$trade} = { };
}
my %TBag_SecondCreations;
for my $second (keys %secondary) {
	$TBag_SecondCreations{$second} = { };
}
my %TBag_SkillCreations;
for my $skill (keys %skills) {
	$TBag_SkillCreations{$skill} = { };
}

###################
### Subroutines ###
###################

# Output the file header.
sub output_header {
  print <<EOH
---------------------------------------------------------------------
--- Item data used for categorization and inventory compression.  ---
--- The trade and skill based data is only a default, it will be  ---
--- calculated on the fly for characters that have those trades   ---
--- or skills.  But these defaults are helpful for getting all    ---
--- reagents into the proper categories.                          ---
---                                                               ---
--- DO NOT EDIT THIS FILE.  IT IS AUTO-GENERATED AND YOUR CHANGES ---
--- WILL BE OVERWRITTEN ON THE NEXT RELEASE OF THE ADDON!         ---
---------------------------------------------------------------------


EOH
}

# Output necessary lua functions for the file.
sub output_footer {
	print <<EOF


function TBag_MergeCreations(TBagCfg,tradetype,new)
  if TBagCfg[tradetype] == nil then
    TBagCfg[tradetype] = {};
  end
  for trade,value in pairs(new) do
    if (type(new[trade]) == "table") then
      if TBagCfg[tradetype][trade] == nil then
        TBagCfg[tradetype][trade] = {};
      end
      for itemid,_ in pairs(new[trade]) do
        TBagCfg[tradetype][trade][itemid] = 1;
      end
    else
      TBagCfg[tradetype][trade] = value;
    end
  end
end

function TBag_RefreshCreations(TBagCfg)
  if (TBagCfg[TBAG_S_TRADES] == nil or TBagCfg[TBAG_S_TRADES][TBAG_S_VERSION] ~= 1) then
    TBagCfg[TBAG_S_TRADES] = TBag_TradeCreations;
  elseif (TBagCfg[TBAG_S_TRADES][TBAG_S_UPDATE] == nil or
          TBagCfg[TBAG_S_TRADES][TBAG_S_UPDATE] < TBag_TradeCreations[TBAG_S_UPDATE]) then
    TBag_MergeCreations(TBagCfg,TBAG_S_TRADES,TBag_TradeCreations);
  end
  if (TBagCfg[TBAG_S_SECOND] == nil or TBagCfg[TBAG_S_SECOND][TBAG_S_VERSION] ~= 1) then
    TBagCfg[TBAG_S_SECOND] = TBag_SecondCreations;
  elseif (TBagCfg[TBAG_S_SECOND][TBAG_S_UPDATE] == nil or
          TBagCfg[TBAG_S_SECOND][TBAG_S_UPDATE] < TBag_TradeCreations[TBAG_S_UPDATE]) then
    TBag_MergeCreations(TBagCfg,TBAG_S_SECOND,TBag_SecondCreations);
  end
  if (TBagCfg[TBAG_S_SKILLS] == nil or TBagCfg[TBAG_S_SKILLS][TBAG_S_VERSION] ~= 1) then
    TBagCfg[TBAG_S_SKILLS] = TBag_SkillCreations;
  elseif (TBagCfg[TBAG_S_SKILLS][TBAG_S_UPDATE] == nil or
          TBagCfg[TBAG_S_SKILLS][TBAG_S_UPDATE] < TBag_SkillCreations[TBAG_S_UPDATE]) then
    TBag_MergeCreations(TBagCfg,TBAG_S_SKILLS,TBag_SkillCreations);
  end
end

function TBag_MergeReagents(TBagCfg,new)
  if TBagCfg[TBAG_S_REAGENT] == nil then
    TBagCfg[TBAG_S_REAGENT] = {};
  end
  for reagent,reagent_value in pairs(new) do
    if (TBagCfg[TBAG_S_REAGENT][reagent] == nil) then
      TBagCfg[TBAG_S_REAGENT][reagent] = {};
    end
    if (type(new[reagent]) == "table") then
      for trade,_ in pairs(new[reagent]) do
        if (TBagCfg[TBAG_S_REAGENT][reagent][trade] == nil) then
          TBagCfg[TBAG_S_REAGENT][reagent][trade] = {};
        end
        for itemid in pairs(new[reagent][trade]) do
          TBagCfg[TBAG_S_REAGENT][reagent][trade][itemid] = 1;
        end
      end
    else
      TBagCfg[TBAG_S_REAGENT][reagent] = reagent_value;
    end
  end
end

function TBag_RefreshReagents(TBagCfg)
  if (TBagCfg[TBAG_S_REAGENT] == nil or TBagCfg[TBAG_S_REAGENT][TBAG_S_VERSION] ~= 1) then
    TBagCfg[TBAG_S_REAGENT] = TBag_Reagents;
  elseif (TBagCfg[TBAG_S_REAGENT][TBAG_S_UPDATE] == nil or
          TBagCfg[TBAG_S_REAGENT][TBAG_S_UPDATE] < TBag_Reagents[TBAG_S_UPDATE]) then
    TBag_MergeReagents(TBagCfg,TBag_Reagents);
  end
end
EOF
}

# Iterate over the reagent hash and output it as valid lua.
sub output_reagents {
	print "local TBag_Reagents = {\n";
	print qq(\t\t[TBAG_S_UPDATE] = "$time",\n);
	print qq(\t\t[TBAG_S_VERSION] = 1,\n);
	foreach my $reagent (sort {$a <=> $b} keys %TBag_Reagents) {
    print qq(\t\t["$reagent"] = {\n);
		foreach my $trade (sort keys %{$TBag_Reagents{$reagent}}) {
      print qq(\t\t\t["$trade"] = {\n);
      foreach my $id (sort {$a <=> $b} @{$TBag_Reagents{$reagent}->{$trade}}) {
        print qq(\t\t\t\t["$id"] =1,\n);
		  }
			print qq(\t\t\t},\n);
		}
    print qq(\t\t},\n);
	}
  print "};\n\n\n";
}

# Iterate over the trade hash and output it as valid lua.
sub output_trades {
	my $var_name = shift;
	my $source_hash = shift;
	print "local $var_name = {\n";
	print qq(\t\t[TBAG_S_UPDATE] = "$time",\n);
	print qq(\t\t[TBAG_S_VERSION] = 1,\n);
	foreach my $trade (sort keys %$source_hash) {
    print qq(\t\t["$trade"] = {\n);
		foreach my $id (sort {$a <=> $b} keys %{$source_hash->{$trade}}) {
      print qq(\t\t\t["$id"] = 1,\n);
		}
		print qq(\t\t},\n);
	}
	print "};\n\n\n";
}

# Iterate over the container items hash and output it as valid lua.
sub output_container_items {
  print "TBag_ContainerItems = {\n";
	print qq(\t\t[TBAG_S_UPDATE] = "$time",\n);
	print qq(\t\t[TBAG_S_VERSION] = 1,\n);
  foreach my $bag_type (sort keys %TBag_ContainerItems) {
    print qq(\t\t["$bag_type"] = {\n);
    foreach my $id (sort {$a <=> $b} @{$TBag_ContainerItems{$bag_type}}) {
      print qq(\t\t\t["$id"] = 1,\n);
		}
		print qq(\t\t},\n);
	}	
	print "};\n\n\n";
}

# Takes a data segment from wowhead and gets the itemids of the
# reagents to make the item.
sub parse_reagents {
	my $data = shift;
	my ($reagents) = $data =~ /reagents:\[(.*)\],/;
	my (@return) = $reagents =~ /\[(\d+),\d+\]/g;
	return \@return;
}

# Takes a data segment and retrieves all the item ids.
sub parse_item_ids {
	my $data = shift;
  my (@return) = $data =~ /\{id:(\d+),/g;
	return \@return;
}

# Finds a data segment matches the template and section in the html page.
sub parse_data {
	my $template = shift;
	my $section_id = shift;
	my $content = shift;

  my ($contain_data) = $content =~ /^new Listview\(\{template:\s+'$template',\s+id:\s+'$section_id'.*?data:\s+\[(.*?)\]\}\)\;$/m;
  return $contain_data;
}		

# Go through all the items made by a given trade and record their
# item ids and the item ids of their reagents into the hash.
sub handle_trade {
	my $mech = shift;
	my $trade = shift;
	my $url = shift;
	my $var = shift;
	my ($trade_content, $trade_data, $ids);

  foreach my $quality (keys %quality_levels) {
		my $url_qual = "$url$quality_levels{$quality}";
	  print STDERR "TRADE [$trade] = $url_qual",$/;
	  $mech->get($url_qual);
	  die("Couldn't get $url") unless $mech->success();
	  $trade_content = $mech->response()->decoded_content;
	  $trade_data = parse_data('item','items',$trade_content);
    $ids = parse_item_ids($trade_data);
	  if ($trade_content =~ /Try filtering your results/) {
		  die("$trade $quality had too many items\n");
	  }
	  print STDERR "Items: ",scalar(@$ids),"\n";
    foreach my $id (@$ids) {
		  $var->{$trade}->{$id} = 1;
		  my $item_url = "${wowhead_url}${item_tag}${id}";
	    print STDERR $item_url,$/;
	    $mech->get($item_url);
		  die("Couldn't get $item_url") unless $mech->success;
	    my $item_contents = $mech->response()->decoded_content;
	    my $item_data = parse_data('spell','created-by',$item_contents);
	    my $item_reagents = parse_reagents($item_data);
		  foreach my $reagent_id (@{$item_reagents}) {
			  $TBag_Reagents{$reagent_id} = {} unless $TBag_Reagents{$reagent_id};
			  $TBag_Reagents{$reagent_id}->{$trade} = [] unless $TBag_Reagents{$reagent_id}->{$trade};
			  push @{$TBag_Reagents{$reagent_id}->{$trade}}, $id;
		  }
	  }
  }	
}

# Go through all the items that can be placed in a given bag type
# and store their ids into the hash.
sub handle_bag_type {
	my $mech = shift;
	my $bag_type = shift;
	my ($url,$page_content,$contain_data,$ids);

	$url = "${wowhead_url}${item_tag}${bag_types{$bag_type}}";
	print STDERR "CONTAINER [$bag_type] = $url",$/;
	$mech->get($url);
	die("Couldn't get url") unless $mech->success();
	$page_content = $mech->response()->decoded_content;
	$contain_data = parse_data('item','can-contain',$page_content);
	$ids = parse_item_ids($contain_data);
	$TBag_ContainerItems{$bag_type} = $ids;
}

# Go through all the different trades and run handle_trade for each.
# Then output all the data.
sub scrape_trade_items {
	my $mech = shift;
	foreach my $trade (keys %trades) {
    handle_trade($mech,$trade,"${wowhead_url}$trades{$trade}",\%TBag_TradeCreations);
	}
  foreach my $second (keys %secondary) {
		handle_trade($mech,$second,"${wowhead_url}$secondary{$second}",\%TBag_SecondCreations);
	}
	foreach my $skill (keys %skills) {
		handle_trade($mech,$skill,"${wowhead_url}$skills{$skill}",\%TBag_SkillCreations);
	}
	output_trades('TBag_TradeCreations',\%TBag_TradeCreations);
	output_trades('TBag_SecondCreations',\%TBag_SecondCreations);
	output_trades('TBag_SkillCreations',\%TBag_SkillCreations);
	output_reagents();
}
			           
# Go through all the different bag types and run handle_bag_type for each.
# Then output all the data.
sub scrape_container_items {
	my $mech = shift;
	foreach my $bag_type (keys %bag_types) {
		handle_bag_type($mech,$bag_type);
	}
  output_container_items();
}

############
### Main ###
############

# Init WWW::Mechanize
my $mech = WWW::Mechanize->new();

# Output the file header.
output_header();

# Scrape what items can be held in what bag types.
scrape_container_items($mech);

# Scrape wowhead of the items created by professions and reagents
scrape_trade_items($mech);

# Output the file footer.
output_footer();
